[package]
name = "solana-lol-program"
version = "0.1.0"
edition = "2021"

[features]
no-entrypoint = []

[dependencies]
solana-program = "1.16.14"

[lib]
name = "solana_lol_program"
crate-type = ["cdylib", "lib"]
doctest = false