[package]
name = "fund_management_cli_client"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-sdk = "1.16.14"
solana-client = "1.16.14"
solana-program = "1.16.14"
borsh = { version ="1.3.0", features = ["derive"] }
