[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
fund_management_program = "EhHV9Fttbudzu9ARRMgWKJqRV4nFY2bTSb4pQYymE92M"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/scawf/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
